spring:
  datasource:
    url: jdbc:mysql://localhost/cloud_tmall?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
tmall: 
  datasource: 
    url: jdbc:mysql://localhost/cloud_tmall?characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
server: 
  port: 9000